# Generated by Django 5.1.7 on 2025-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trello_member_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
