# Generated by Django 5.1.7 on 2025-03-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_trello_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='trello_member_id',
        ),
    ]
