# Generated by Django 5.1.7 on 2025-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_task_trello_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trello_member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
