# Generated by Django 5.1.7 on 2025-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trellousermapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='trello_member_id',
        ),
        migrations.DeleteModel(
            name='TrelloUserMapping',
        ),
    ]
