# Generated by Django 5.1.7 on 2025-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_task_assigned_to_task_trello_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_member_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
