# Generated by Django 5.1.7 on 2025-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_trellomember'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
