# Generated by Django 5.1.7 on 2025-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_task_full_name_task_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
