# Generated by Django 5.1.7 on 2025-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_sent_2',
            field=models.BooleanField(default=False),
        ),
    ]
