# Generated by Django 5.1.7 on 2025-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_task_email_sent_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_sent_3',
            field=models.BooleanField(default=False),
        ),
    ]
