# Generated by Django 5.1.7 on 2025-04-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_task_completed_on_task_score_counted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='score_counted',
        ),
        migrations.RemoveField(
            model_name='trellomember',
            name='historical_score',
        ),
        migrations.RemoveField(
            model_name='trellomember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trellomember',
            name='total_tasks_counted',
        ),
    ]
