# Generated by Django 5.1.7 on 2025-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_task_completed_on_remove_task_score_counted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='score_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trellomember',
            name='historical_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trellomember',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trellomember',
            name='total_tasks_counted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
