# Generated by Django 5.1.7 on 2025-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_task_completed_on_task_score_counted_and_more'),
    ]

    operations = [
    ]
