# Generated by Django 5.1.7 on 2025-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_task_completed_on_task_score_counted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_of_everyday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
