# Generated by Django 5.1.7 on 2025-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_boss_detail_of_everyday'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manual_score_override',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
